# Generated by Django 4.2.16 on 2025-03-28 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_admission',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_leaving',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='others',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_mobile_number',
        ),
    ]
