# Generated by Django 4.2.16 on 2024-10-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_leaving',
            field=models.DateField(blank=True, null=True),
        ),
    ]
