# Generated by Django 4.2.16 on 2025-01-19 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_date_of_leaving'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
    ]
