# Generated by Django 4.2.16 on 2025-01-20 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0008_theme'),
        ('test_olish', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='subject',
        ),
        migrations.AddField(
            model_name='question',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='corecode.theme'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testsession',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='corecode.theme'),
            preserve_default=False,
        ),
    ]
