# Generated by Django 4.2.16 on 2025-01-25 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_olish', '0002_remove_question_subject_remove_testsession_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_olish.option'),
        ),
    ]
