# Generated by Django 4.2.16 on 2025-01-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('SF', 'Staff'), ('ST', 'Student'), ('TR', 'Teacher'), ('AD', 'Admin'), ('HD', 'HeadTeacher')], default='ST', max_length=2, verbose_name='User Type'),
        ),
    ]
