# Generated by Django 4.2.16 on 2025-01-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ST', 'Student'), ('TR', 'Teacher'), ('AD', 'Admin'), ('HD', 'HeadTeacher')], default='ST', max_length=2, verbose_name='User Type'),
        ),
    ]
