# Generated by Django 4.2.16 on 2025-02-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ST', 'Student'), ('TR', 'Teacher'), ('AD', 'Admin'), ('HD', 'HeadTeacher'), ('KT', 'kattakon')], default='ST', max_length=2, verbose_name='User Type'),
        ),
    ]
