# Generated by Django 4.2.16 on 2024-10-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corecode', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(to='students.student'),
        ),
    ]
