# Generated by Django 4.2.16 on 2024-10-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0003_alter_class_options_class_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='class_instance',
        ),
        migrations.AlterField(
            model_name='mark',
            name='classwork_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark',
            name='homework_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
