# Generated by Django 4.2.16 on 2024-10-10 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0004_remove_mark_class_instance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='marked_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mark',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
