# Generated by Django 4.2.16 on 2024-10-10 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0005_alter_mark_marked_at_alter_mark_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='class_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='corecode.class'),
            preserve_default=False,
        ),
    ]
