# Generated by Django 4.2.16 on 2024-10-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0006_mark_class_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='class_id',
            new_name='class_instance',
        ),
    ]
