# Generated by Django 4.2.16 on 2025-01-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0008_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='students',
        ),
    ]
