# Generated by Django 4.2.16 on 2025-01-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0009_remove_class_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='related_topics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
