# Generated by Django 4.2.16 on 2025-02-04 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0011_tuman_theme_class_name_school_class_shcool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.class'),
        ),
    ]
