# Generated by Django 4.2.16 on 2025-02-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0012_alter_theme_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='num_questions',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='theme',
            name='timer',
            field=models.IntegerField(default=1200),
        ),
    ]
