# Generated by Django 4.2.16 on 2025-02-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0013_theme_num_questions_theme_timer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='shcool',
            new_name='school',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='class_name',
        ),
        migrations.AddField(
            model_name='theme',
            name='class_name',
            field=models.ManyToManyField(blank=True, to='corecode.class'),
        ),
    ]
