# Generated by Django 4.2.16 on 2025-03-12 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0015_monthsession_payment_usersessionaccess'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersessionaccess',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usersessionaccess',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='usersessionaccess',
            name='session',
        ),
        migrations.RemoveField(
            model_name='usersessionaccess',
            name='user',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='UserSessionAccess',
        ),
    ]
