# Generated by Django 4.2.16 on 2024-10-09 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='class_name',
        ),
    ]
