# Generated by Django 4.2.16 on 2024-10-09 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0003_alter_class_options_class_students_and_more'),
        ('staffs', '0002_remove_teacher_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='corecode.subject'),
        ),
    ]
