# Generated by Django 4.2.16 on 2025-02-04 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0012_alter_theme_class_name'),
        ('staffs', '0006_kattakon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.school'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.subject'),
        ),
    ]
