# Generated by Django 4.2.16 on 2025-02-08 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0013_theme_num_questions_theme_timer'),
        ('staffs', '0007_alter_director_school_alter_teacher_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='school',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='corecode.school'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='corecode.subject'),
        ),
    ]
